name: Lint

on:
  push:
    branches: [main, dev]
    paths:
      - '**.dart'
      - 'pubspec.yaml'
      - 'analysis_options.yaml'
  pull_request:
    branches: [main, dev]
    paths:
      - '**.dart'
      - 'pubspec.yaml'
      - 'analysis_options.yaml'

jobs:
  analyze:
    name: dart analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Analyze
        run: dart analyze lib/ bin/ --fatal-infos
